### ISSUE TITLE
Compute is not connected

### ISSUE THREAD

**Issue by jzuilkowski** [fog/fog-oraclecloud#3]
Somewhere between line 19 and 22 of lib/fog/oraclecloud.rb, you need to add:

autoload :Compute, File.expand_path('../oraclecloud/compute', __FILE__)

Or none of the methods will be found

**Comment by Joelith** [comment]
Hi jzuilkowski, are you sure? That line is above on Line 9. You need to refer to compute instances through Fog::Compute[:oraclecloud] and not Fog::OracleCloud[:compute]. This aligns with the way the other providers use the core fog modules (compute, networking and storage) and use their own namespace for their different stuff (mainly PaaS)

**Comment by jzuilkowski** [comment]
You are correct.  I could not get it to work and was unsure why.  I refreshed my copy and it worked
